In [40]:
from tensorflow.keras.preprocessing.text import one_hot


In [41]:
# sentences
sent = [
    'the glass of milk',
    'the cup of tea',
    'i m a good boy',
    'i m a good developer',
    'understand the meaning of words',
    'your videos are good'
]

In [42]:
sent

['the glass of milk',
 'the cup of tea',
 'i m a good boy',
 'i m a good developer',
 'understand the meaning of words',
 'your videos are good']

In [43]:
# define the vocab size
vocab_size = 10000

In [44]:
# one hot representation
one_hot_rep = [one_hot(words, vocab_size)for words in sent ]

In [45]:
one_hot_rep

[[5931, 8795, 8440, 7010],
 [5931, 938, 8440, 1200],
 [5524, 9214, 7647, 8687, 5134],
 [5524, 9214, 7647, 8687, 7047],
 [4214, 5931, 6710, 8440, 1983],
 [1303, 6210, 5031, 8687]]

In [46]:
# word enbedding representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
# from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [47]:
import numpy as np


In [48]:
sent_length = 8
embedded_doc = pad_sequences(one_hot_rep, padding='pre',maxlen=sent_length)
print(embedded_doc)

[[   0    0    0    0 5931 8795 8440 7010]
 [   0    0    0    0 5931  938 8440 1200]
 [   0    0    0 5524 9214 7647 8687 5134]
 [   0    0    0 5524 9214 7647 8687 7047]
 [   0    0    0 4214 5931 6710 8440 1983]
 [   0    0    0    0 1303 6210 5031 8687]]


In [49]:
#  feature representation
dim=10


In [50]:
model = Sequential()
model.add(Embedding(vocab_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\Hp\OneDrive\Desktop\ANN-PROJECT-1\venv\Lib\site-packages\keras\src\layers\core\embedding.py:123: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [51]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [52]:
model.predict(embedded_doc)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step


array([[[-0.02070316,  0.02974553,  0.04420724, -0.0291411 ,
          0.02962314, -0.0260993 ,  0.04515375, -0.00834428,
          0.04206354,  0.02719418],
        [-0.02070316,  0.02974553,  0.04420724, -0.0291411 ,
          0.02962314, -0.0260993 ,  0.04515375, -0.00834428,
          0.04206354,  0.02719418],
        [-0.02070316,  0.02974553,  0.04420724, -0.0291411 ,
          0.02962314, -0.0260993 ,  0.04515375, -0.00834428,
          0.04206354,  0.02719418],
        [-0.02070316,  0.02974553,  0.04420724, -0.0291411 ,
          0.02962314, -0.0260993 ,  0.04515375, -0.00834428,
          0.04206354,  0.02719418],
        [ 0.04956246,  0.01893064, -0.0385089 ,  0.03876594,
          0.03617437, -0.021148  , -0.02384452,  0.04492015,
          0.0316379 ,  0.00662565],
        [-0.01612425, -0.04174029, -0.02831285, -0.04061095,
         -0.03375635, -0.04077394, -0.00607735, -0.03734756,
         -0.03939886, -0.0245268 ],
        [-0.03571566, -0.04500636,  0.01553929, -0.0

In [53]:
embedded_doc[0]

array([   0,    0,    0,    0, 5931, 8795, 8440, 7010], dtype=int32)

<!--simple RNN  -->